### ISSUE TITLE
Translations ("Move" gizmo) get reset when a fairing base is updated (or loaded).

### ISSUE THREAD

**Issue by Katniss218** [KSP-RO/ProceduralFairings#10]
If the part is attached to the fairing base, and moved, then after that fairing base is updated (e.g. value changed, craft loaded, etc.) that moved part moves back to the node, thus negating the usefulness of the "Move" gizmo.

**How to reproduce:**
- Place a fairing base.
- Place any part on any of the nodes of that fairing (top, bottom, stage, sides).
- Move the part (via "Move" gizmo)
- Do either either one of:
    - Edit one of the values of the fairing base (size, height, etc).
    - Save and reload the craft.

**Comment by Katniss218** [comment]
Update:

Surface attachment works normally, with all translations/rotations/etc. being preserved.

**Comment by DRVeyl** [comment]
Fixed in https://github.com/KSP-RO/ProceduralFairings/commit/05ca60cdb9d32cad07c80a857853d1d86244a63b in my dev branch.  

Check out the pre-release: https://github.com/KSP-RO/ProceduralFairings/releases/tag/v1.8.2-beta1

**Comment by siimav** [comment]
Haven't gotten any such issues with v6.0 beta
