### ISSUE TITLE
Hollow bases aren't quite hollow

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProceduralFairings#11]
Per DebugTools, a Hollow Interstage Ring has a hollow collider matching the ring, but also a tiny spherical collider right in the middle. One case where this cause a problem is if an engine is intended to thrust "through" the adapter, and ends up being occluded by that small dot. (there's probably other cases)

![](https://media.discordapp.net/attachments/319857228905447436/682699659491541042/Screen_Shot_2020-02-27_at_16.23.56.png)

All the payload/interstage bases have that same central collider; arguably it's only a problem for the Hollow Ring and Hollow Truss variants, as they're the ones that seem to invite sticking something through the hole.

(the Hollow Truss is an odd case; Debug Tools shows the colliders for all variants at once. if they really are all active at once, that adds more potential for unseen clipping)

**Comment by DRVeyl** [comment]
I'm not familiar enough with Blender, but I cannot find the central collider in it.  According to DebugStuff, it is present in all the different Fairing Bases, though it appears to be the "Surface Attach Collider."  If anyone's sufficiently familiar with some of the model tools to adjust this, that'd be great.

**Comment by pap1723** [comment]
Working on this

**Comment by DRVeyl** [comment]
Fixed in https://github.com/KSP-RO/ProceduralFairings/pull/27
