### ISSUE TITLE
node sizes, taking into account addons

### ISSUE THREAD

**Issue by azeroth1977** [KSP-RO/ProceduralFairings#19]
These calculations create incorrect node sizes for 1.875m parts, that appeared in addons
sorry, cant make pool request :)
ProceduralFairings/FairingBase.cs

126: public int TopNodeSize => Mathf.RoundToInt((Mode == BaseMode.Adapter ? topSize : baseSize) / diameterStepLarge);
        public int BottomNodeSize => Mathf.RoundToInt(baseSize / diameterStepLarge);
        public int InterstageNodeSize => Math.Max(1, TopNodeSize - 1);
        public int FairingBaseNodeSize => Math.Max(1, TopNodeSize - 1);

**Comment by DRVeyl** [comment]
I'm not sure what you mean by "addons."  Screenshots may help illustrate your issue.
The node sizes have been fairly inconsistent.  The code snippet referenced is meant to try to put some consistency towards it.
Note those changes I believe are only in the 6.x pre-release.
