### ISSUE TITLE
Fairing bases nodes are a little wonky, moving slider and back solves it

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/ProceduralFairings#2]
When adding a new fairing base to a vessel, and with or without moving the slider for side nodes count before attaching a side, makes some of the nodes or even all but one disappear.
Detaching the side, moving the slider away and back; the nodes reappear and the base works as intended.

I had this now for weeks in my RO RP-1 setup.

I will provide a log as soon as I reproduced this issue.

**Comment by Gordon-Dry** [comment]
Perhaps this is the solution, let's check it first:
https://github.com/KSP-RO/ProceduralFairings/pull/3

**Comment by DRVeyl** [comment]
ProcFairings doesn't produce a lot of usable debug data.  However, while I'm reworking things and adding some fixes for colliders and center-of-mass handling for the fairing sides, I'll make sure the side nodes on the base start with an expected (?) value.

**Comment by siimav** [comment]
Pretty sure that's fixed in v6.0 beta
