### ISSUE TITLE
Procedural fairings think they're infront of the heatshield and overheat

### ISSUE THREAD

**Issue by TransparentElemental** [KSP-RO/ProceduralFairings#20]
KSP 1.8.1
ProceduralFairings 1.8.3
ProceduralFairings - For Everything! 0.3.0
![screenshot1434](https://user-images.githubusercontent.com/56821387/112474200-5b2df180-8d80-11eb-8ef1-b74312536593.png)
![screenshot1435](https://user-images.githubusercontent.com/56821387/112474212-5ec17880-8d80-11eb-9336-57bb11bb46ad.png)
![screenshot1436](https://user-images.githubusercontent.com/56821387/112474221-61bc6900-8d80-11eb-8258-e91b9ba64329.png)
![screenshot1437](https://user-images.githubusercontent.com/56821387/112474229-64b75980-8d80-11eb-8386-5fc37e17c920.png)
![screenshot1438](https://user-images.githubusercontent.com/56821387/112474251-6a14a400-8d80-11eb-99b6-e57e908554b2.png)
![screenshot1439](https://user-images.githubusercontent.com/56821387/112474265-6f71ee80-8d80-11eb-9d56-4c458e853b8a.png)

**Comment by DRVeyl** [comment]
*Possibly* ~~fixed~~ improved by <https://github.com/KSP-RO/ProceduralFairings/commit/0064f9aa7f5fd44876d2b566b648c86ff6d4bc9b>
Does this still happen with a recent pre-release of PF v6?
I'm looking to actually release PF v6 ... no earlier than 12 JUN 2021.
