### ISSUE TITLE
Disable Decoupler on base doesn't disable decoupler

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/ProceduralFairings#34]
The Decoupler: Enabled toggle in the VAB doesn't actually disable the decoupler; it only removes it from the staging order. In flight, the decoupler can still be operated.

Per discord discussion, the intent was to make the decoupler non-functional in flight as well.

Main known impact is that in rp-1, disabling it reduces the base cost; this doesn't make sense if the decoupler remains functional.

https://discord.com/channels/319857228905447436/620690446540341261/895437148134731777

**Comment by DRVeyl** [comment]
https://github.com/KSP-RO/ProceduralFairings/commit/e804019fe48e6981473a5a74c5de41109edd027e
