### ISSUE TITLE
KSP 1.8 Base Texture Error

### ISSUE THREAD

**Issue by friznit** [KSP-RO/ProceduralFairings#4]
As reported on the forum a couple of weeks ago, I am led to understand that the path to the shader referenced for the blue fairing guidelines changed in KSP 1.8 so is currently showing a default pink texture.

Ref line 370 here

https://github.com/KSP-RO/ProceduralFairings/blob/master/Source/ProceduralFairings/FairingBase.cs#L370%60

**Comment by siimav** [comment]
Fixed in the latest release
