### ISSUE TITLE
Fairing density isn't clamped to minDensity when loading a craft in the editor

### ISSUE THREAD

**Issue by ghost** [KSP-RO/ProceduralFairings#48]
It's very easy to forget about fairings tech upgrade when loading a design from a previous save. This leads to inadvertent cheating.
There should be a validation of fairings tech level, similar to avionics and tanks.

**Comment by NathanKell** [comment]
I think what you mean is "fairing density isn't clamped to min density on load".

**Comment by ghost** [comment]
I meant checking tech level when building the vessel.  Just clamping high tech level fairings to higher density creates another issue - the design is modified without the user even knowing about it.  If clamping is implemented then it should probably show a popup message on craft load, that the design had higher tech fairings than currently researched, so the density was increased and the craft might not perform as well as expected.

**Comment by NathanKell** [comment]
PF upgrades work just like ROSolar and RealAntenna tech levels, not like RF engine or tank configs.
