### ISSUE TITLE
Interstage fairing issue

### ISSUE THREAD

**Issue by adrianstu98** [KSP-RO/ProceduralFairings#53]
Hi! I have a problem ussing the interstage fairing:
https://imgur.com/a/DWZRbJM
I want to "create" the Vega fairing between stage 1 and 2 but the fairing seems to be fixed to the top stage. Im using ksp 1.12.4 and tweakscale. This is an issue that happens with the stock fairings too and i dont know how to make it.
Thanks for the attention!

**Comment by siimav** [comment]
Looks like help was provided on the forums.
https://forum.kerbalspaceprogram.com/topic/184187-18-procedural-fairings/?do=findComment&comment=4317311
