### ISSUE TITLE
Fairing collider has incorrect size

### ISSUE THREAD

**Issue by Katniss218** [KSP-RO/ProceduralFairings#9]
When scaling proc fairings, the collider is prety accurate with smaller shapes, but with bigger ones it's not.

As the fairing base's size increases, the difference between fairing's size and collider size also increases, leading to wildly incorrect colliders with sizes as low as 10m. This can lead to clipping, and Rapid Unscheduled Dissassemblies.

**How to reproduce:**
Sadly no screenshot, as it won't capture the mouse pointer, but to replicate, place a fairing base, attach the fairing to it.
Position the camera perpendicurarly to the node, and move the cursor towards the fairing. Take note of how close the fairing selects.

Now increase the base & top size to something big. Repeat the experiment.

**Comment by DRVeyl** [comment]
This is possibly related to https://github.com/KSP-RO/ProceduralFairings/issues/6 ?  Making sure I'm reading correctly, the collider issue is with the fairing, not the fairing base.  It is most noticable when scaling to large diameter bases because that makes for large fairings.  Accurate?

**Comment by Katniss218** [comment]
> This is possibly related to #6 ? Making sure I'm reading correctly, the collider issue is with the fairing, not the fairing base. It is most noticable when scaling to large diameter bases because that makes for large fairings. Accurate?

Might be, fairings are in general quite buggy in atmo, but I don't understand that nearly enough to do anything.
Yes, collider issue is with the fairing itself, **not the base**. And no, the "fairing itself" collider seems to have different scaling factor when placed on larger fairing bases. Seems like if the fairing base is scaled 6x (from 1m to 6m) then Fairing Piece Itself ™ collider is scaled to ~6.75m. Similarly for 10m, 15m, etc. The bigger it gets, the bigger the `ColliderDiameter / VisualDiameter` gets

That's only an observation though.

**Comment by DRVeyl** [comment]
Believe this is fixed [or at least mitigated...] in https://github.com/KSP-RO/ProceduralFairings/commit/11ae41e661548db530dc740b9a89d073704426b4 in my dev branch.

**Comment by DRVeyl** [comment]
Fixed/mitigated with the release: https://github.com/KSP-RO/ProceduralFairings/releases/tag/v1.8.2
